#!/usr/bin/env bash

export CREATOR_FREE_ONLY=1
export PAID_FALLBACK_DISABLED=1

unset OPENAI_API_KEY
unset REPLICATE_API_TOKEN
unset REPLICATE_API_KEY
unset ANTHROPIC_API_KEY

export OPENAI_API_KEY=""
export REPLICATE_API_TOKEN=""
export REPLICATE_API_KEY=""
export ANTHROPIC_API_KEY=""
